"""Dataclasses describing inputs/outputs for compliance logging."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Sequence


@dataclass
class ModelInput:
    """Input passed to a predictive model."""

    symbol: str
    features: Sequence[str]


@dataclass
class ModelOutput:
    """Output generated by a predictive model."""

    signal: str
    score: float
    timestamp: str | None = None


@dataclass
class RegulatoryRecord:
    """Structured record stored for compliance."""

    symbol: str
    datetime: str
    metric: Dict[str, float] = field(default_factory=dict)
