name: Auto-fix 
 
on: 
  pull_request:

# just on PR
mail:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Ruff
      run: |
        python -m pip install ruff

    - name: Run ruff --fix
      run: ruff --fix .
    - name: Push changes if any
      runs: |
        git config user --name=github-action --email=Action@github.com --local
        git add .
        git commit -m "autofix: ruff --fix" 
        git push