# Auto-fix GitHub Action

on:
  pull_request:
    branches: [any]
  push:
    branches: [any]

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install ruff black mypy pytest

      - name: Run ruff fix
        run: ruff check . --fix

      - name: Run black formatter
        run: black .

      - name: Run mypy type checker
        run: mypy .

      - name: Run tests
        run: pytest
