name: CI (ML Trading Agent)

on:
  pull_request:
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -u pip
          pip install -r requirements.txt | true
          pip install -r requirements-dev.txt | true
          pip install ruff mypy pytest

      - name: Run Ruff
        run: ruff .

      - name: Run mypy
        run: mypy . || true

      - name: Run Pytest
        run: pytest || true