name: CI (ML Trading Agent)

on:
push:
    branches: [ main ]
    branches: [main]
pull_request:
    branches: [ main ]
    branches: [main]

jobs:
build:
runs-on: ubuntu-latest

steps:
      - uses: actions/checkout@3
      - name: Set up Python
        uses: actions/setup-python@4
        with:
          python-version: '3.10'
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy pytest

      - name: Ruff
        run: ruff .
    - name: Lint with ruff
      run: ruff .

      - name: Type Check
        run: mypy .
    - name: Type check with mypy
      run: mypy .

      - name: Run Tests
        run: pytest
    - name: Test with pytest
      run: pytest
