name: CI (ML Trading Agent)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name: Set up Python
        uses: actions/setup-python@4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff
        run: ruff .

      - name: Type Check
        run: mypy .

      - name: Run Tests
        run: pytest