name: "Auto Fix Files"

on:
  push:
    branches: [main]

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install tools
        run: |
          pip install ruff black isort
          npm install -g markdownlint-cli

      - name: Auto-fix Python
        run: |
          ruff check --fix --unsafe-fixes .
          black .
          isort .

      - name: Auto-fix Markdown
        run: markdownlint --fix '**/*.md'
