name: Validate Uploaded Files

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -u pip
          pip install ruff mypy pyamllint json
      - name: Validate Python Files
        run: ruff . && mypy .
      - name: Validate YAML Files
        run: yamllint .
      - name: Validate JSON Files
        run: jsonlnt *.json
      - name: Validate Markdown Files
        run: echo "Markdown check not implemented yet."