name: "Validate Uploaded Files"
on:
  push:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install tools
        run: pip install ruff mypy yamllint jsonlint

      - name: Validate Python
        run: ruff .

      - name: Validate YAML
        run: yamllint .

      - name: Validate JSON
        run: echo 'error:JSON validation not implemented'

      - name: Validate MD
        run: doctorlint '.markdown'
